apiVersion: v1
kind: Service
metadata:
  name: checkinpro-svc
  namespace: dev
spec:
  ports:
  - port: 5200
    protocol: TCP
    targetPort: 5200
  selector:
    app: checkinpro-api
  sessionAffinity: None
  type: ClusterIP